apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: demo-app-secrets
  namespace: default
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: demo-app-slnn
        envSlug: dev
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: default
  managedSecretReference:
    secretName: demo-app-synced-secrets
    secretNamespace: default
