apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: gitops-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: argocd.kubelaba.com
      service: https://argocd-server.argocd:443
      originRequest:
        noTLSVerify: true
    - hostname: infisical.kubelaba.com
      service: http://infisical-infisical-standalone-infisical.infisical:8080
    - hostname: k8s-api.kubelaba.com
      service: https://kubernetes.default.svc:443
      originRequest:
        noTLSVerify: true
    - service: http_status:404
